# Generated by Django 4.1.4 on 2022-12-28 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_companylogo_job_employee_job_facebook_and_more'),
        ('taggit', '0005_auto_20220424_2025'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='location'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/users/profile.jpg', upload_to='media/users')),
                ('birth_day', models.DateField(blank=True, default=None, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('about', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(upload_to='media/resumes')),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('company', models.CharField(blank=True, max_length=250)),
                ('save_job', models.ManyToManyField(blank=True, default=None, related_name='save_job', to='jobs.job')),
                ('skills', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('message', models.TextField(blank=True, default="We are pleased to inform you that you have been selected for the [Position] role at [Company]. We believe that your skills and experience make you a strong fit for this role and we are excited to have you join our team.We will be in touch with you soon to finalize the details of your employment, including your start date and any necessary paperwork. In the meantime, please don't hesitate to reach out to us with any questions you may have.Congratulations on this exciting new opportunity. We look forward to working with you.")),
                ('unread', models.BooleanField(default=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('message_id', models.IntegerField(default=0)),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
