# Generated by Django 4.1.4 on 2022-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_birth_day_account_location_profile_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='company',
            field=models.TextField(blank=True, default="We are pleased to inform you that you have been selected for the [Position] role at [Company]. We believe that your skills and experience make you a strong fit for this role and we are excited to have you join our team.We will be in touch with you soon to finalize the details of your employment, including your start date and any necessary paperwork. In the meantime, please don't hesitate to reach out to us with any questions you may have.Congratulations on this exciting new opportunity. We look forward to working with you."),
        ),
        migrations.AddField(
            model_name='invite',
            name='title',
            field=models.TextField(blank=True, default="We are pleased to inform you that you have been selected for the [Position] role at [Company]. We believe that your skills and experience make you a strong fit for this role and we are excited to have you join our team.We will be in touch with you soon to finalize the details of your employment, including your start date and any necessary paperwork. In the meantime, please don't hesitate to reach out to us with any questions you may have.Congratulations on this exciting new opportunity. We look forward to working with you."),
        ),
        migrations.AddField(
            model_name='invite',
            name='type',
            field=models.TextField(blank=True, default="We are pleased to inform you that you have been selected for the [Position] role at [Company]. We believe that your skills and experience make you a strong fit for this role and we are excited to have you join our team.We will be in touch with you soon to finalize the details of your employment, including your start date and any necessary paperwork. In the meantime, please don't hesitate to reach out to us with any questions you may have.Congratulations on this exciting new opportunity. We look forward to working with you."),
        ),
    ]
