# Generated by Django 4.1.4 on 2022-12-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invite_company_invite_title_invite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='company',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='invite',
            name='message',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='invite',
            name='title',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='invite',
            name='type',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='media/resumes'),
        ),
    ]
